//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long ID { get; set; }
        public System.Guid ExternalID { get; set; }
        public long CustomerID { get; set; }
        public Nullable<long> MechanicID { get; set; }
        public Nullable<long> DealerID { get; set; }
        public long VehicleID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Mechanic Mechanic { get; set; }
        public virtual Service Service { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
