//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long ID { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public long Room_ID { get; set; }
        public string Status { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
